/**
 * The Following files contains the unchangable code of variable
 */
PORTNO = 4000;

// DATA STATUS
exports.OK = 200;
exports.CREATED = 201;
exports.ACCEPTED = 202;
exports.BAD_REQUEST = 400;
exports.NOT_FOUND = 404;

// MESSAGES
exports.RECORD_FOUND = "PRODUCT DATA FOUND!!";
exports.RECORD_NOT_FOUND = "PRODUCT DATA NOT FOUND!!";
exports.REGISTERED = "PRODUCT REGISTRATION SUCCESSFULLY!!";
exports.REGISTER_FAILED = "PRODUCT REGISTRATION FAILED..";
exports.UPDATED = "PRODUCT Data Updated SUCCESSFULLY!!";
exports.UPDATE_FAILED = "UPDATION FAILED!!";
exports.REMOVED = "PRODUCT SUCCESSFULLY REMOVED!!";
exports.REMOVE_FAIL = "RECORD NOT DELETED!!";
